unset ROCR_VISIBLE_DEVICES

REWARD_FUNCTION_PATH="./verl/verl/utils/reward_score/planner_em_format.py"
TRAIN_DATA="./data/planner/train_filtered.parquet"
VAL_DATA="./data/planner/test_2000.parquet"
EXPERIMENT_NAME="test"
MAX_TURNS=4

python3 -m verl.trainer.main_ppo \
	algorithm.adv_estimator="grpo" \
	data.train_batch_size=128 \
	data.val_batch_size=256 \
	data.max_prompt_length=4096 \
	data.max_response_length=4096 \
	data.max_start_length=3072 \
	data.max_obs_length=500 \
	data.filter_overlong_prompts=True \
	data.truncation='error' \
	data.return_raw_chat=True \
	data.reward_fn_key='data_source' \
	data.filter_overlong_prompts_workers=32 \
	actor_rollout_ref.model.path=Qwen/Qwen2.5-3B \
	actor_rollout_ref.actor.optim.lr=5e-7 \
	actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.285 \
	actor_rollout_ref.model.use_remove_padding=True \
	actor_rollout_ref.actor.ppo_mini_batch_size=256 \
	actor_rollout_ref.actor.ppo_max_token_len_per_gpu=14000 \
	actor_rollout_ref.actor.use_dynamic_bsz=True \
	actor_rollout_ref.actor.use_kl_loss=True \
	actor_rollout_ref.actor.kl_loss_coef=0.001 \
	actor_rollout_ref.actor.kl_loss_type=low_var_kl \
	actor_rollout_ref.model.enable_gradient_checkpointing=True \
	actor_rollout_ref.actor.fsdp_config.param_offload=False \
	actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
	actor_rollout_ref.rollout.max_model_len=4572 \
	actor_rollout_ref.rollout.max_num_batched_tokens=4572 \
	actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=64 \
	actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
	actor_rollout_ref.rollout.name=vllm \
	actor_rollout_ref.rollout.mode=sync \
	actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
	actor_rollout_ref.rollout.n=5 \
	actor_rollout_ref.rollout.seed=0 \
	actor_rollout_ref.rollout.response_length=1024 \
	actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=256 \
	actor_rollout_ref.ref.fsdp_config.param_offload=True \
	algorithm.use_kl_in_reward=False \
	algorithm.no_think_rl=false \
	actor_rollout_ref.rollout.val_kwargs.temperature=1.0 \
	actor_rollout_ref.rollout.temperature=1.0 \
	reward_model.reward_manager='planner' \
	reward_model.reward_kwargs.score=1.0 \
	reward_model.reward_kwargs.structure_format_score=0.2 \
	reward_model.reward_kwargs.final_format_score=0.1 \
	reward_model.reward_kwargs.retrieval_score=0.0 \
	custom_reward_function.path="$REWARD_FUNCTION_PATH" \
	trainer.critic_warmup=0 \
	trainer.val_before_train=False \
	trainer.logger=['console','wandb'] \
	trainer.project_name='planner_rl' \
	trainer.experiment_name=$EXPERIMENT_NAME \
	trainer.n_gpus_per_node=1 \
	trainer.nnodes=1 \
	trainer.save_freq=10 \
	trainer.validation_data_dir=./validation_data/$EXPERIMENT_NAME \
	trainer.test_freq=1834 \
	data.train_files="$TRAIN_DATA" \
	data.val_files="$VAL_DATA" \
	max_turns=$MAX_TURNS \
	reranker.url="http://localhost:8005/rerank/batch" \
	reranker.topk=3 \
	reranker.retriever_initial_topk=15 \
	reranker.return_full_documents=false \
	trainer.total_epochs=2
